import Link from "next/link";
import { getViewerContext } from "@/lib/viewer-context";
import { getEventTeamRemaps } from "@/lib/event-team-remaps";
import { eventTeamNumber } from "@/lib/tba-team-identity";
import { AppShell, PageHeader } from "@/components/app-shell";
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import { LocalDateTime } from "@/components/local-date-time";
import { matchLabel } from "@/lib/match-label";
export default async function TeamDetail({params}:{params:Promise<{teamId:string}>}){const {teamId}=await params;const supabase=await createClient();const {data:team}=await supabase.from("teams").select("id,team_number,name").eq("id",teamId).maybeSingle();if(!team)notFound();const viewer=await getViewerContext();const {data:eventLink}=viewer?.activeEvent?await supabase.from("event_teams").select("team_id").eq("event_id",viewer.activeEvent.id).eq("team_id",team.id).maybeSingle():{data:null};const remaps=await getEventTeamRemaps(eventLink?viewer?.activeEvent?.id:null);const {data:submissions}=await supabase.from("match_submissions").select("id,status,payload,submitted_at,matches(match_number,match_type,tba_match_key)").eq("team_id",teamId).order("submitted_at",{ascending:false}).limit(20);return <AppShell active="Teams"><PageHeader eyebrow="Team detail" title={`${eventTeamNumber(team.team_number,remaps)} · ${team.name}`}>{eventLink&&viewer?.activeEvent&&<Link className="link" href={`/events/${viewer.activeEvent.event_key}/teams/${team.team_number}`}>Open {viewer.activeEvent.name} team page</Link>}</PageHeader><div className="page-grid"><section className="card"><div className="card-head"><h2>Match history</h2><span className="muted">{submissions?.length??0} visible entries</span></div>{submissions?.length?submissions.map((s:any)=><div className="list-row" key={s.id}><div><strong>{s.matches?matchLabel(s.matches):"Match unavailable"}</strong><div className="muted">{s.submitted_at?<LocalDateTime value={s.submitted_at}/>:"Draft"}</div></div><span className={`tag ${s.status === "submitted" ? "complete":"pending"}`}>{s.status}</span></div>):<p className="muted">No submissions are visible for this team yet.</p>}</section><aside className="card"><h2>Scouting note</h2><p className="muted" style={{lineHeight:1.7}}>Photos remain private and are accessed with short-lived signed URLs after database authorization.</p></aside></div></AppShell>}
