"use client";

import Link from "next/link";
import { ChevronDown, ExternalLink } from "lucide-react";
import { ResponsiveContainer, Line, LineChart, CartesianGrid, Tooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";
import { MatchReportSummary } from "@/components/scouting-payload";
import { AppSelect } from "@/components/app-select";

type MetricKey = "totalFuel" | "autoFuel" | "teleopFuel" | "fouls" | "defense" | "broken";
const metricOptions: { key: MetricKey; label: string; color: string }[] = [{ key: "totalFuel", label: "Avg fuel", color: "#f24444" }, { key: "autoFuel", label: "Auto fuel", color: "#f2bf44" }, { key: "teleopFuel", label: "Teleop fuel", color: "#60a5fa" }, { key: "fouls", label: "Fouls", color: "#c084fc" }, { key: "defense", label: "Defense", color: "#34d399" }, { key: "broken", label: "Broken", color: "#fb7185" }];
export type TimelineMatch = { id: string; label: string; matchType: "qualification" | "playoff" | "practice"; roundOrder: number; alliance: "red" | "blue"; outcome: "win" | "loss" | "tie" | "pending"; score: string; tbaUrl?: string; report?: { id: string; payload: Record<string, unknown>; scout: string }; hasScout: boolean; totalFuel: number | null; autoFuel: number | null; teleopFuel: number | null; fouls: number | null; defense: number | null; broken: number | null };
const label = (outcome: TimelineMatch["outcome"]) => outcome === "win" ? "Won" : outcome === "loss" ? "Lost" : outcome === "tie" ? "Tied" : "Pending";
const value = (number: number | null) => number === null ? "—" : number.toFixed(2);

export function TeamMatchTimeline({ matches, teamNames }: { matches: TimelineMatch[]; teamNames: Record<string, string> }) {
  const [metrics, setMetrics] = useState<MetricKey[]>(["totalFuel", "autoFuel", "teleopFuel"]);
  const [openReport, setOpenReport] = useState<string | null>(null);
  const [matchScope, setMatchScope] = useState<"competitive" | "practice">("competitive");
  const visibleMatches = matches.filter((match) => matchScope === "practice" ? match.matchType === "practice" : match.matchType !== "practice");
  const hasData = visibleMatches.some((match) => match.hasScout);
  const chartData = visibleMatches.map((match) => ({ ...match, match: match.label, ...Object.fromEntries(metricOptions.map(({ key }) => [key, match[key] ?? undefined])) }));
  const toggleMetric = (key: MetricKey) => setMetrics((current) => current.includes(key) ? current.length === 1 ? current : current.filter((item) => item !== key) : [...current, key].slice(-4));
  return <section className="card team-timeline-card"><div className="card-head"><div><h2>Match timeline</h2><p className="muted">Results and scouting coverage.</p></div><div className="team-timeline-head-actions"><AppSelect value={matchScope} onValueChange={(value) => { setMatchScope(value as "competitive" | "practice"); setOpenReport(null); }} ariaLabel="Match timeline scope" options={[{ value: "competitive", label: "Qualifications + playoffs" }, { value: "practice", label: "Practice matches" }]}/><span className="muted">{visibleMatches.filter((match) => match.hasScout).length} / {visibleMatches.length} scouted</span></div></div>{visibleMatches.length ? <>{hasData ? <><div className="team-timeline-metrics" role="group" aria-label="Chart metrics">{metricOptions.map((metric) => <button type="button" key={metric.key} className={metrics.includes(metric.key) ? "active" : ""} onClick={() => toggleMetric(metric.key)}>{metric.label}</button>)}</div><div className="team-timeline-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, bottom: 0, left: -16 }}><CartesianGrid stroke="#303640" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="match" tick={{ fill: "#969dab", fontSize: 10 }} tickLine={false} axisLine={false}/><YAxis tick={{ fill: "#969dab", fontSize: 10 }} tickLine={false} axisLine={false} width={32}/><Tooltip contentStyle={{ background: "#15181d", border: "1px solid #303640", borderRadius: 8, fontSize: 12 }} labelStyle={{ color: "#f3f4f6", fontWeight: 700 }} formatter={(item) => typeof item === "number" ? item.toFixed(2) : item ?? "—"}/>{metricOptions.filter((metric) => metrics.includes(metric.key)).map((metric) => <Line key={metric.key} type="monotone" dataKey={metric.key} name={metric.label} stroke={metric.color} strokeWidth={metric.key === "totalFuel" ? 3 : 2} connectNulls={false} dot={{ r: 3, fill: metric.color, strokeWidth: 0 }}/>)}</LineChart></ResponsiveContainer></div></> : <p className="muted team-timeline-empty">No submitted {matchScope === "practice" ? "practice" : "qualification or playoff"} match reports yet. Official results will still appear below.</p>}<div className="team-timeline-list">{visibleMatches.map((match) => {
    const isOpen = openReport === match.id;
    const reportActionLabel = isOpen ? `Hide details for ${match.label}` : `Show details for ${match.label}`;
    return <article key={match.id} className={`team-timeline-row ${match.alliance} ${match.hasScout ? "scouted" : "missing"}`}><div className="team-timeline-match"><strong>{match.label}</strong><span className={match.alliance}>{match.alliance}</span></div><div className="team-timeline-result"><strong>{label(match.outcome)}</strong><span>{match.score}</span></div><div className="team-timeline-coverage"><strong>{match.hasScout ? "Scouted" : "Missing"}</strong><span>{match.hasScout ? `Fuel ${value(match.totalFuel)}` : "No submitted report"}</span></div><div className="team-timeline-actions">{match.report && <><Link className="timeline-action-button" href={`/submissions/${match.report.id}`}>Report</Link><button type="button" className="timeline-disclosure" aria-label={reportActionLabel} aria-expanded={isOpen} onClick={() => setOpenReport((current) => current === match.id ? null : match.id)}><ChevronDown size={16} aria-hidden="true"/></button></>}{match.tbaUrl && <Link className="timeline-action-button" href={match.tbaUrl} target="_blank">TBA <ExternalLink size={14} aria-hidden="true"/></Link>}</div>{isOpen && match.report && <div className="team-timeline-report"><div className="team-timeline-report-head"><span>{`${match.report.scout}'s report`}</span></div><MatchReportSummary payload={match.report.payload} teamNames={teamNames}/></div>}</article>;
  })}</div></> : <p className="muted">No {matchScope === "practice" ? "practice" : "qualification or playoff"} matches have been published for this team yet.</p>}</section>;
}
