import Link from "next/link";
import { AppShell, PageHeader } from "@/components/app-shell";
import { createClient } from "@/lib/supabase/server";
import { LiveRefresh } from "@/components/live-refresh";
import { type TeamScoutEntry, calculateScoutStats, competitiveMatchEntries, groupByTeam, selectedMatchReportEntries } from "@/lib/scouting-stats";
import { PreScoutTable } from "./pre-scout-table";
import { officialFuelAverages } from "@/lib/official-fuel-stats";
import { SummaryTable } from "./summary-table";
import { type TbaRanking, type TbaSortInfo, asNumber, fetchTbaRankings, officialClimb, tbaMetric } from "@/lib/tba-event-stats";

type PageProps = { params: Promise<{ eventId: string }>; searchParams: Promise<{ sort?: string; dir?: string }> };
export default async function SummaryPage({ params, searchParams }: PageProps) {
  const { eventId: eventKey } = await params; const query = await searchParams; const supabase = await createClient();
  const { data: event } = await supabase.from("events").select("id,name,event_key,is_manual").eq("event_key", eventKey).maybeSingle();
  if (!event) return <AppShell active="Summary"><PageHeader eyebrow="Event summary" title="Event unavailable."/><section className="card"><p className="muted">This event could not be found.</p></section></AppShell>;
  const [{ data: eventTeams }, { data: entries }, { data: reportSources }, { data: preScoutEntries }, { data: officialMatches }, { rankings, sortInfo, oprs, apiError }] = await Promise.all([supabase.from("event_teams").select("team_id,teams(team_number,name)").eq("event_id", event.id), (supabase as any).from("scouting_entries").select("id,match_id,team_id,payload,matches(id,match_type)").eq("event_id", event.id).eq("entry_type", "match").eq("status", "submitted"), (supabase as any).from("match_report_sources").select("team_id,match_key,selected_entry_id").eq("event_id", event.id), (supabase as any).from("scouting_entries").select("team_id,payload,created_at").eq("event_id", event.id).eq("entry_type", "pre_scout").eq("status", "submitted").order("created_at", { ascending: false }), (supabase as any).from("matches").select("red_teams,blue_teams,tba_score_breakdown").eq("event_id", event.id).eq("status", "played"), event.is_manual ? Promise.resolve({ rankings: [] as TbaRanking[], sortInfo: [] as TbaSortInfo[], oprs: {} as Record<string, number>, apiError: "" }) : fetchTbaRankings(event.event_key)]);
  const entriesByTeam = groupByTeam(entries);
  const tbaByTeam = new Map(rankings.map((ranking) => [Number(String(ranking.team_key ?? "").replace("frc", "")), ranking]));
  const rows = (eventTeams ?? []).map((link: any) => { const reports = selectedMatchReportEntries(competitiveMatchEntries(entriesByTeam.get(link.team_id) ?? []), reportSources ?? []); const stats = calculateScoutStats(reports); const tba = tbaByTeam.get(link.teams?.team_number); const officialFuel = officialFuelAverages(officialMatches ?? [], link.team_id); return { team: link.teams, teamId: link.team_id, tba, opr: asNumber(oprs[`frc${link.teams?.team_number}`]), stats, maxFuel: stats.peakFuel, ...officialClimb(officialMatches ?? [], link.team_id), tbaTotalFuel: officialFuel?.totalFuel ?? tbaMetric(tba, sortInfo, /total.*fuel|avg.*match/i), tbaAutoFuel: officialFuel?.autoFuel ?? tbaMetric(tba, sortInfo, /auto.*fuel/i), tbaTransitionFuel: tbaMetric(tba, sortInfo, /transition.*fuel/i), tbaTeleopFuel: officialFuel?.teleopFuel ?? tbaMetric(tba, sortInfo, /teleop.*fuel/i), tbaEndgameFuel: tbaMetric(tba, sortInfo, /endgame.*fuel/i) }; });
  const metric = (row: any, key: string) => key === "team" ? row.team?.team_number : key === "rank" ? asNumber(row.tba?.rank || 99999) : key in row.stats ? asNumber(row.stats[key]) : asNumber(row[key]); const sort = query.sort ?? "opr"; const dir = query.dir === "asc" ? "asc" : "desc"; rows.sort((a: any, b: any) => { const diff = metric(a, sort) - metric(b, sort); return diff * (dir === "asc" ? 1 : -1); });
  const latestPreScout = new Map<string, any>(); for (const entry of preScoutEntries ?? []) if (!latestPreScout.has(entry.team_id)) latestPreScout.set(entry.team_id, entry.payload);
  const preScoutRows = (eventTeams ?? []).sort((a: any,b: any) => a.teams?.team_number - b.teams?.team_number).map((link: any) => { const report: any = latestPreScout.get(link.team_id) ?? {}; return { id: link.team_id, teamNumber: link.teams?.team_number ?? "—", teamName: link.teams?.name ?? "Unknown team", autos: report.autos ?? "—", activeShift: report.active_shift ?? "—", inactiveShift: report.inactive_shift ?? "—", traversal: report.traversal ?? "—", averagePieces: report.average_pieces ?? "—", withThem: report.with_them ?? "—", againstThem: report.against_them ?? "—" }; });
  return <AppShell active="Summary"><LiveRefresh tables={["scouting_entries", "match_report_sources", "matches"]} eventId={event.id}/><PageHeader eyebrow={event.name} title="Scouting summary."/><section className="card summary-card"><div className="card-head"><h2>Live team data</h2><div className="row-actions"><Link className="button secondary" href={`/events/${eventKey}/compare`}>Compare teams</Link><Link className="button secondary" href={`/events/${eventKey}/teams`}>Team directory</Link></div></div>{apiError && <p className="error">{apiError}</p>}<SummaryTable eventKey={eventKey} rows={rows as any} sort={sort} dir={dir}/></section><section className="card summary-card section"><div className="card-head"><div><h2>Pre-scout sheet</h2><p className="muted">Every team’s latest pre-scout report in one spreadsheet-style view.</p></div></div><PreScoutTable rows={preScoutRows}/></section></AppShell>;
}
